# Generated by Django 4.2.7 on 2025-04-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='traceback',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
