# Generated by Django 4.2.7 on 2025-04-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='time',
            new_name='post_time',
        ),
    ]
